version: '3.5'

networks:
    nginx:
        external: true

services:
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=zii-research-thingies
      - POSTGRES_PASSWORD=IJzDL3O3STZbkpjgZIqm
    ports:
      - 5432
    volumes:
      - /var/apps/zii-research-thingies.data/postgresql:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    hostname: redis
    image: redis:alpine
    restart: always
    volumes:
      - /var/apps/zii-research-thingies.data/redis:/data

  app:
    image: zii-research-thingies
    build:
      context: .
    environment:
      - RAILS_MAX_THREADS=5
      - RAILS_LOG_TO_STDOUT=1
      - DATABASE_URL=postgres://postgres:IJzDL3O3STZbkpjgZIqm@db:5432/zii-research-thingies
      - REDIS_URL=redis://redis:6379/0
      - APP_HOST=zii-research-thingies.syan.me
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=zii-research-thingies.syan.me
      - LETSENCRYPT_HOST=zii-research-thingies.syan.me
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    networks:
      - nginx
      - default
    ports:
      - 3000
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 30s
      start_period: 1m

  worker:
    image: zii-research-thingies
    build:
      context: .
    environment:
      - RAILS_MAX_THREADS=5
      - RAILS_LOG_TO_STDOUT=1
      - DATABASE_URL=postgres://postgres:IJzDL3O3STZbkpjgZIqm@db:5432/zii-research-thingies
      - REDIS_URL=redis://redis:6379/0
      - APP_HOST=zii-research-thingies.syan.me
    command: bundle exec sidekiq
    hostname: worker
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    networks:
      - nginx
      - default
    restart: always
    healthcheck:
      test: "ps ax | grep -v grep | grep sidekiq"
      interval: 1m
      start_period: 1m
